services:
  - type: web
    name: chat-app-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: ChatApp
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://chat-app-frontend.onrender.com

  - type: static
    name: chat-app-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_BASE_URL
        value: https://chat-app-backend.onrender.com
